--------------------------------------------------------
--  File created - Thursday-September-08-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNT_DETAILS
--------------------------------------------------------

  CREATE TABLE "ACCOUNT_DETAILS" ("ACCOUNT_NO" VARCHAR2(30), "CUSTOMER_ID" VARCHAR2(30), "SAVING_ACCOUNT_TYPE_ID" VARCHAR2(30), "CURRENT_ACCOUNT_TYPE_ID" VARCHAR2(30), "FIXED_DEPOSIT_ACCOUNT_TYPE_ID" VARCHAR2(30), "ACCOUNT_STATUS" VARCHAR2(20))
REM INSERTING into ACCOUNT_DETAILS
SET DEFINE OFF;
Insert into ACCOUNT_DETAILS (ACCOUNT_NO,CUSTOMER_ID,SAVING_ACCOUNT_TYPE_ID,CURRENT_ACCOUNT_TYPE_ID,FIXED_DEPOSIT_ACCOUNT_TYPE_ID,ACCOUNT_STATUS) values ('AC79220000','C4002','S120','C1000','FD125','Inactive');
Insert into ACCOUNT_DETAILS (ACCOUNT_NO,CUSTOMER_ID,SAVING_ACCOUNT_TYPE_ID,CURRENT_ACCOUNT_TYPE_ID,FIXED_DEPOSIT_ACCOUNT_TYPE_ID,ACCOUNT_STATUS) values ('AC79220001','C4003','S121','C1001','FD126','Inactive');
Insert into ACCOUNT_DETAILS (ACCOUNT_NO,CUSTOMER_ID,SAVING_ACCOUNT_TYPE_ID,CURRENT_ACCOUNT_TYPE_ID,FIXED_DEPOSIT_ACCOUNT_TYPE_ID,ACCOUNT_STATUS) values ('AC79220002','C4004','S122','C1002','FD127','Inactive');
Insert into ACCOUNT_DETAILS (ACCOUNT_NO,CUSTOMER_ID,SAVING_ACCOUNT_TYPE_ID,CURRENT_ACCOUNT_TYPE_ID,FIXED_DEPOSIT_ACCOUNT_TYPE_ID,ACCOUNT_STATUS) values ('AC79220003','C4005','S123','C1003','FD128','Inactive');
Insert into ACCOUNT_DETAILS (ACCOUNT_NO,CUSTOMER_ID,SAVING_ACCOUNT_TYPE_ID,CURRENT_ACCOUNT_TYPE_ID,FIXED_DEPOSIT_ACCOUNT_TYPE_ID,ACCOUNT_STATUS) values ('AC79220004','C4006','S124','C1004','FD129','Inactive');
--------------------------------------------------------
--  DDL for Index ACCOUNT_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ACCOUNT_NO_PK" ON "ACCOUNT_DETAILS" ("ACCOUNT_NO")
--------------------------------------------------------
--  Constraints for Table ACCOUNT_DETAILS
--------------------------------------------------------

  ALTER TABLE "ACCOUNT_DETAILS" MODIFY ("ACCOUNT_NO" NOT NULL ENABLE)
  ALTER TABLE "ACCOUNT_DETAILS" MODIFY ("ACCOUNT_STATUS" NOT NULL ENABLE)
  ALTER TABLE "ACCOUNT_DETAILS" ADD CONSTRAINT "ACCOUNT_NO_PK" PRIMARY KEY ("ACCOUNT_NO") USING INDEX  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT_DETAILS
--------------------------------------------------------

  ALTER TABLE "ACCOUNT_DETAILS" ADD CONSTRAINT "CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER_DETAILS" ("CUSTOMER_ID") ENABLE
  ALTER TABLE "ACCOUNT_DETAILS" ADD CONSTRAINT "SAVING_ACCOUNT_TYPE_ID_FK" FOREIGN KEY ("SAVING_ACCOUNT_TYPE_ID") REFERENCES "SAVINGS_DETAILS" ("SAVING_ACCOUNT_TYPE_ID") ENABLE
  ALTER TABLE "ACCOUNT_DETAILS" ADD CONSTRAINT "CURRENT_ACCOUNT_TYPE_ID_FK" FOREIGN KEY ("CURRENT_ACCOUNT_TYPE_ID") REFERENCES "CURRENT_DETAILS" ("CURRENT_ACCOUNT_TYPE_ID") ENABLE
  ALTER TABLE "ACCOUNT_DETAILS" ADD CONSTRAINT "FIXED_DEPOSIT_ACCOUNT_TYPE_ID_FK" FOREIGN KEY ("FIXED_DEPOSIT_ACCOUNT_TYPE_ID") REFERENCES "FIXED_DEPOSIT" ("FIXED_DEPOSIT_ACCOUNT_TYPE_ID") ENABLE
