--------------------------------------------------------
--  File created - Thursday-September-08-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CURRENT_DETAILS
--------------------------------------------------------

  CREATE TABLE "CURRENT_DETAILS" ("CURRENT_ACCOUNT_TYPE_ID" VARCHAR2(20), "CUSTOMER_ID" VARCHAR2(50), "FIRST_NAME" VARCHAR2(50), "LAST_NAME" VARCHAR2(50), "CURRENT_BALANCE" NUMBER(10,0), "OVERDRAFT_BALANCE" NUMBER(10,0), "OVERDRAFT_ROI" NUMBER(10,0), "OPENING_DATE" DATE)
REM INSERTING into CURRENT_DETAILS
SET DEFINE OFF;
Insert into CURRENT_DETAILS (CURRENT_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,CURRENT_BALANCE,OVERDRAFT_BALANCE,OVERDRAFT_ROI,OPENING_DATE) values ('C1000','C4002','pRADEEP','SAWANT',1000,5000,7,to_date('07-SEP-22','DD-MON-RR'));
Insert into CURRENT_DETAILS (CURRENT_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,CURRENT_BALANCE,OVERDRAFT_BALANCE,OVERDRAFT_ROI,OPENING_DATE) values ('C1001','C4003','RAM','SAWANT',1000,5000,7,to_date('07-SEP-22','DD-MON-RR'));
Insert into CURRENT_DETAILS (CURRENT_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,CURRENT_BALANCE,OVERDRAFT_BALANCE,OVERDRAFT_ROI,OPENING_DATE) values ('C1002','C4004','RAM','SAWANT',1000,5000,7,to_date('07-SEP-22','DD-MON-RR'));
Insert into CURRENT_DETAILS (CURRENT_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,CURRENT_BALANCE,OVERDRAFT_BALANCE,OVERDRAFT_ROI,OPENING_DATE) values ('C1003','C4005','YASH','SAWANT',1000,5000,7,to_date('07-SEP-22','DD-MON-RR'));
Insert into CURRENT_DETAILS (CURRENT_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,CURRENT_BALANCE,OVERDRAFT_BALANCE,OVERDRAFT_ROI,OPENING_DATE) values ('C1004','C4006','MUSKAN','SAWANT',1000,5000,7,to_date('07-SEP-22','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index CURRENT_ACCOUNT_TYPE_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURRENT_ACCOUNT_TYPE_ID_PK" ON "CURRENT_DETAILS" ("CURRENT_ACCOUNT_TYPE_ID")
--------------------------------------------------------
--  Constraints for Table CURRENT_DETAILS
--------------------------------------------------------

  ALTER TABLE "CURRENT_DETAILS" MODIFY ("CURRENT_ACCOUNT_TYPE_ID" NOT NULL ENABLE)
  ALTER TABLE "CURRENT_DETAILS" MODIFY ("FIRST_NAME" NOT NULL ENABLE)
  ALTER TABLE "CURRENT_DETAILS" MODIFY ("LAST_NAME" NOT NULL ENABLE)
  ALTER TABLE "CURRENT_DETAILS" MODIFY ("CURRENT_BALANCE" NOT NULL ENABLE)
  ALTER TABLE "CURRENT_DETAILS" MODIFY ("OVERDRAFT_BALANCE" NOT NULL ENABLE)
  ALTER TABLE "CURRENT_DETAILS" MODIFY ("OVERDRAFT_ROI" NOT NULL ENABLE)
  ALTER TABLE "CURRENT_DETAILS" ADD CONSTRAINT "CURRENT_ACCOUNT_TYPE_ID_PK" PRIMARY KEY ("CURRENT_ACCOUNT_TYPE_ID") USING INDEX  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table CURRENT_DETAILS
--------------------------------------------------------

  ALTER TABLE "CURRENT_DETAILS" ADD CONSTRAINT "CURRENT_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER_DETAILS" ("CUSTOMER_ID") ENABLE
