--------------------------------------------------------
--  File created - Thursday-September-08-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER_DETAILS
--------------------------------------------------------

  CREATE TABLE "CUSTOMER_DETAILS" ("FIRST_NAME" VARCHAR2(30), "LAST_NAME" VARCHAR2(30), "ADDRESS_LINE_1" VARCHAR2(50), "ADDRESS_LINE_2" VARCHAR2(50), "ADDRESS_LINE_3" VARCHAR2(50), "CITY" VARCHAR2(20), "STATE" VARCHAR2(20), "ZIP" NUMBER(6,0), "PHONE" NUMBER(10,0), "CELL" NUMBER(10,0), "EMAIL" VARCHAR2(30), "CUSTOMER_ID" VARCHAR2(10), "LOGIN_ID" VARCHAR2(20), "REGISTRATION_STATUS" VARCHAR2(10))
REM INSERTING into CUSTOMER_DETAILS
SET DEFINE OFF;
Insert into CUSTOMER_DETAILS (FIRST_NAME,LAST_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,CITY,STATE,ZIP,PHONE,CELL,EMAIL,CUSTOMER_ID,LOGIN_ID,REGISTRATION_STATUS) values ('VINEET','GAUDA','PR','WB','G.B.','THANE','MAH',400615,1234546,987654,'VIN@123GMAIL.COM','C4002','INB1001','active');
Insert into CUSTOMER_DETAILS (FIRST_NAME,LAST_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,CITY,STATE,ZIP,PHONE,CELL,EMAIL,CUSTOMER_ID,LOGIN_ID,REGISTRATION_STATUS) values ('PRATIK','MISHRA','NG','SW','LBS','THANE','MAH',400610,154584,3487856,'PRA@123GMAIL.COM','C4003','INB1001','active');
Insert into CUSTOMER_DETAILS (FIRST_NAME,LAST_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,CITY,STATE,ZIP,PHONE,CELL,EMAIL,CUSTOMER_ID,LOGIN_ID,REGISTRATION_STATUS) values ('VIVEK','GAUDA','PR','WB','G.B.','THANE','MAH',400615,1234546,987654,'VIV@123GMAIL.COM','C4004','INB1001','inactive');
Insert into CUSTOMER_DETAILS (FIRST_NAME,LAST_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,CITY,STATE,ZIP,PHONE,CELL,EMAIL,CUSTOMER_ID,LOGIN_ID,REGISTRATION_STATUS) values ('PRADEEP','SAWANT','KA','KL','KW','THANE','MAH',400615,875458,345455,'PSA@123GMAIL.COM','C4005','INB1001','active');
Insert into CUSTOMER_DETAILS (FIRST_NAME,LAST_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,CITY,STATE,ZIP,PHONE,CELL,EMAIL,CUSTOMER_ID,LOGIN_ID,REGISTRATION_STATUS) values ('SURAJ','GUPTA','VA','VS','VI','WADALA','MAH',400814,9676843,156856,'SGA@123GMAIL.COM','C4006','INB1001','active');
--------------------------------------------------------
--  DDL for Index CUSTOMER_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CUSTOMER_ID_PK" ON "CUSTOMER_DETAILS" ("CUSTOMER_ID")
--------------------------------------------------------
--  Constraints for Table CUSTOMER_DETAILS
--------------------------------------------------------

  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("FIRST_NAME" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("LAST_NAME" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("ADDRESS_LINE_1" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("ADDRESS_LINE_2" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("ADDRESS_LINE_3" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("CITY" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("STATE" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("ZIP" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("PHONE" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("CELL" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("EMAIL" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" MODIFY ("REGISTRATION_STATUS" NOT NULL ENABLE)
  ALTER TABLE "CUSTOMER_DETAILS" ADD CONSTRAINT "CUSTOMER_ID_PK" PRIMARY KEY ("CUSTOMER_ID") USING INDEX  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER_DETAILS
--------------------------------------------------------

  ALTER TABLE "CUSTOMER_DETAILS" ADD CONSTRAINT "LOGIN_ID_FK" FOREIGN KEY ("LOGIN_ID") REFERENCES "LOGIN_DETAILS" ("LOGIN_ID") ENABLE
