--------------------------------------------------------
--  File created - Thursday-September-08-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FIXED_DEPOSIT
--------------------------------------------------------

  CREATE TABLE "FIXED_DEPOSIT" ("FIXED_DEPOSIT_ACCOUNT_TYPE_ID" VARCHAR2(20), "CUSTOMER_ID" VARCHAR2(50), "FIRST_NAME" VARCHAR2(50), "LAST_NAME" VARCHAR2(50), "PRINCIPAL" NUMBER(10,0), "TENURE" NUMBER(10,0), "ROI" NUMBER(10,2), "DURATION_PASSED" NUMBER(10,0), "MATURITY_AMT" NUMBER(10,0))
REM INSERTING into FIXED_DEPOSIT
SET DEFINE OFF;
Insert into FIXED_DEPOSIT (FIXED_DEPOSIT_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,PRINCIPAL,TENURE,ROI,DURATION_PASSED,MATURITY_AMT) values ('FD125','C4002','VINEET','GAUDA',10000,12,4.5,6,15000);
Insert into FIXED_DEPOSIT (FIXED_DEPOSIT_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,PRINCIPAL,TENURE,ROI,DURATION_PASSED,MATURITY_AMT) values ('FD126','C4003','VIVEK','GAUDA',10000,24,5,6,17000);
Insert into FIXED_DEPOSIT (FIXED_DEPOSIT_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,PRINCIPAL,TENURE,ROI,DURATION_PASSED,MATURITY_AMT) values ('FD127','C4004','PRATIK','MISHRA',10000,12,4.5,6,15000);
Insert into FIXED_DEPOSIT (FIXED_DEPOSIT_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,PRINCIPAL,TENURE,ROI,DURATION_PASSED,MATURITY_AMT) values ('FD128','C4005','PRADEEP','SAWANT',10000,12,4.5,6,15000);
Insert into FIXED_DEPOSIT (FIXED_DEPOSIT_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,PRINCIPAL,TENURE,ROI,DURATION_PASSED,MATURITY_AMT) values ('FD129','C4006','SURAJ','GUPTA',10000,12,4.5,6,15000);
--------------------------------------------------------
--  DDL for Index FIXED_DEPOSIT_ACCOUNT_TYPE_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FIXED_DEPOSIT_ACCOUNT_TYPE_ID_PK" ON "FIXED_DEPOSIT" ("FIXED_DEPOSIT_ACCOUNT_TYPE_ID")
--------------------------------------------------------
--  Constraints for Table FIXED_DEPOSIT
--------------------------------------------------------

  ALTER TABLE "FIXED_DEPOSIT" MODIFY ("FIXED_DEPOSIT_ACCOUNT_TYPE_ID" NOT NULL ENABLE)
  ALTER TABLE "FIXED_DEPOSIT" MODIFY ("FIRST_NAME" NOT NULL ENABLE)
  ALTER TABLE "FIXED_DEPOSIT" MODIFY ("LAST_NAME" NOT NULL ENABLE)
  ALTER TABLE "FIXED_DEPOSIT" MODIFY ("PRINCIPAL" NOT NULL ENABLE)
  ALTER TABLE "FIXED_DEPOSIT" MODIFY ("TENURE" NOT NULL ENABLE)
  ALTER TABLE "FIXED_DEPOSIT" MODIFY ("ROI" NOT NULL ENABLE)
  ALTER TABLE "FIXED_DEPOSIT" MODIFY ("DURATION_PASSED" NOT NULL ENABLE)
  ALTER TABLE "FIXED_DEPOSIT" MODIFY ("MATURITY_AMT" NOT NULL ENABLE)
  ALTER TABLE "FIXED_DEPOSIT" ADD CONSTRAINT "FIXED_DEPOSIT_ACCOUNT_TYPE_ID_PK" PRIMARY KEY ("FIXED_DEPOSIT_ACCOUNT_TYPE_ID") USING INDEX  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table FIXED_DEPOSIT
--------------------------------------------------------

  ALTER TABLE "FIXED_DEPOSIT" ADD CONSTRAINT "FIXED_DEPOSIT_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER_DETAILS" ("CUSTOMER_ID") ENABLE
