--------------------------------------------------------
--  File created - Thursday-September-08-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SAVINGS_DETAILS
--------------------------------------------------------

  CREATE TABLE "SAVINGS_DETAILS" ("SAVING_ACCOUNT_TYPE_ID" VARCHAR2(30), "CUSTOMER_ID" VARCHAR2(30), "FIRST_NAME" VARCHAR2(50), "LAST_NAME" VARCHAR2(50), "CURRENT_BALANCE" NUMBER(10,2), "RATE_OF_INTEREST" NUMBER(10,2), "OPENING_DATE" DATE)
REM INSERTING into SAVINGS_DETAILS
SET DEFINE OFF;
Insert into SAVINGS_DETAILS (SAVING_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,CURRENT_BALANCE,RATE_OF_INTEREST,OPENING_DATE) values ('S120','C4002','VINEET','GAUDA',19595,6,to_date('07-SEP-22','DD-MON-RR'));
Insert into SAVINGS_DETAILS (SAVING_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,CURRENT_BALANCE,RATE_OF_INTEREST,OPENING_DATE) values ('S121','C4003','VIVEK','GAUDA',19595,6,to_date('07-SEP-22','DD-MON-RR'));
Insert into SAVINGS_DETAILS (SAVING_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,CURRENT_BALANCE,RATE_OF_INTEREST,OPENING_DATE) values ('S122','C4004','PRADEEP','SAWANT',19595,6,to_date('07-SEP-22','DD-MON-RR'));
Insert into SAVINGS_DETAILS (SAVING_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,CURRENT_BALANCE,RATE_OF_INTEREST,OPENING_DATE) values ('S123','C4005','PRATIK','MISHRA',19595,6,to_date('07-SEP-22','DD-MON-RR'));
Insert into SAVINGS_DETAILS (SAVING_ACCOUNT_TYPE_ID,CUSTOMER_ID,FIRST_NAME,LAST_NAME,CURRENT_BALANCE,RATE_OF_INTEREST,OPENING_DATE) values ('S124','C4006','SURAJ','GUPTA',19595,6,to_date('07-SEP-22','DD-MON-RR'));
--------------------------------------------------------
--  DDL for Index SAVING_ACCOUNT_TYPE_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAVING_ACCOUNT_TYPE_ID_PK" ON "SAVINGS_DETAILS" ("SAVING_ACCOUNT_TYPE_ID")
--------------------------------------------------------
--  Constraints for Table SAVINGS_DETAILS
--------------------------------------------------------

  ALTER TABLE "SAVINGS_DETAILS" MODIFY ("SAVING_ACCOUNT_TYPE_ID" NOT NULL ENABLE)
  ALTER TABLE "SAVINGS_DETAILS" MODIFY ("FIRST_NAME" NOT NULL ENABLE)
  ALTER TABLE "SAVINGS_DETAILS" MODIFY ("LAST_NAME" NOT NULL ENABLE)
  ALTER TABLE "SAVINGS_DETAILS" MODIFY ("CURRENT_BALANCE" NOT NULL ENABLE)
  ALTER TABLE "SAVINGS_DETAILS" MODIFY ("RATE_OF_INTEREST" NOT NULL ENABLE)
  ALTER TABLE "SAVINGS_DETAILS" ADD CONSTRAINT "SAVING_ACCOUNT_TYPE_ID_PK" PRIMARY KEY ("SAVING_ACCOUNT_TYPE_ID") USING INDEX  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table SAVINGS_DETAILS
--------------------------------------------------------

  ALTER TABLE "SAVINGS_DETAILS" ADD CONSTRAINT "SAVING_CUSTOMER_ID_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER_DETAILS" ("CUSTOMER_ID") ENABLE
